FEATURE: Create node template definition yaml dump from node subtree
Flowpack/Flowpack.NodeTemplates pull request #40
Opened 2023-05-22 13:53 UTC by mhsdesign

`flow nodeTemplate:fromSubtree <nodeIdentifier>`

closes: #37

2023-05-30 08:34 UTC, Sebobo requested changes
Great change, left some comments

2023-05-30 08:34 UTC, Sebobo commented on Classes/NodeTemplateDumper/NodeTemplateDumper.php
> +                $readableId = [
Check should be `isAutoGenerated` && `isContentCollection`

2023-05-30 08:34 UTC, Sebobo commented on Classes/NodeTemplateDumper/NodeTemplateDumper.php
> +    private function nodeTemplateFromDocumentNodes(array $nodes, Comments $comments): array
The `from` methods should be merged by adding a simple `isDocumentNode` condition where needed

2023-05-30 08:34 UTC, Sebobo commented on Classes/NodeTemplateDumper/NodeTemplateDumper.php
> +                $readableId = $node->getName() . 'Tethered';
I would prefer `AutoCreated` like it's called in other places

2023-05-30 08:34 UTC, Sebobo commented on Classes/NodeTemplateDumper/NodeTemplateDumper.php
> +    public function createNodeTemplateYamlDumpFromSubtree(Node $startingNode): string
Can we use `NodeInterface` everywhere instead of the 3 variants?

2023-05-30 08:34 UTC, Sebobo commented on Classes/NodeTemplateDumper/NodeTemplateDumper.php
> +            $label = $configuration["ui"]["label"] ?? null;
Use single quotes everywhere

2023-05-31 21:09 UTC, lorenzulrich reviewed
Thanks, great work!

2023-05-31 21:09 UTC, lorenzulrich commented on Configuration/Testing/NodeTypes.yaml
> +                text: "im never created"
> i'm never created

2023-06-01 09:16 UTC, mhsdesign commented on Classes/Command/NodeTemplateCommandController.php
> +    public function fromSubtreeCommand(string $startingNodeId, string $workspaceName = 'live'): void
Hi thanks for your review. The naming `subtree` is taken from the new ESCR, where you can actually get with one sql query the whole subtree:

[`ContentSubgraphInterface::findSubtree`](https://github.com/neos/neos-development-collection/blob/2a6c0ff4ee880da095056be436e003607305d708/Neos.ContentRepository.Core/Classes/Projection/ContentGraph/ContentSubgraphInterface.php#L104-L111)


A subtree will look like [this](https://github.com/neos/neos-development-collection/blob/2a6c0ff4ee880da095056be436e003607305d708/Neos.ContentRepository.Core/Classes/Projection/ContentGraph/Subtree.php#L10)

so i like to keep the name `subtree` (maybe we can add the prefix node so people understand its node releated?: `NodeSubtree`)

but i agree that something like a verb could also be a nice addition to the command name:

```sh
# original
flow nodeTemplate:fromSubtree <nodeIdentifier>

# your proposal
flow nodeTemplate:createConfigurationForSubtree <nodeIdentifier>

# your other proposal
flow nodeTemplate:dumpConfigurationForNodeTree <nodeIdentifier>

# my idea:
flow nodeTemplate:createFromNodeSubtree <nodeIdentifier>

``` 

@Sebobo and me decided for now on `nodeTemplate:createFromNodeSubtree`

2023-06-01 11:52 UTC, Sebobo approved these changes

2023-06-01 11:52 UTC, merged